#source 'https://github.com/CocoaPods/Specs.git'

ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'

target 'MobileBackendIOS' do
pod 'AWSCore'
pod 'AWSCognito'
pod 'AWSS3'
pod 'AWSAPIGateway', '~> 2.2.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
